# Generated by Django 4.0.6 on 2023-01-30 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_moviedata_typ'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviedata',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to=''),
        ),
    ]
