# Generated by Django 4.0.6 on 2023-01-30 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_moviedata_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviedata',
            name='image',
            field=models.ImageField(default='Images/default.jpg', upload_to='Image/'),
        ),
    ]
